.TH pekwm "1" "October 2008" "pekwm 0.1.8" "User Commands"
.SH NAME
pekwm \- a tabbed window manager
.SH SYNOPSIS
.TP
\fPpekwm\fP [\fIoptions\fP]
.SH DESCRIPTION
Pekwm is a tabbed window manager which focuses on being highly
configurable. Pekwm has a rich feature set including:

  * Autoproperties, set properties and group windows automatically based on type or title.
  * Keychains, multi-level keybindings.
  * XRandR and Xinerama support.
.PP
For more information about the pekwm project and for full
documentation, visit http://www.pekwm.org.
.SH OPTIONS
.TP
\fB\--help\fR
Show help information.
.TP
\fB\--version\fR
Show version information.
.TP
\fB\--info\fR
Show information about compiled in features.
.TP
\fB\--display\fR \fIDISPLAY\fR
Connect to DISPLAY instead of DISPLAY set in environment.
.TP
\fB\--config\fR \fICONFIG\fR
Use CONFIG file instead of default ~/.pekwm/config
