.nh
.TH pekwm\_panel 1 "March 2021" pekwm\_sreenshot "User Manual"

.SH NAME
.PP
pekwm\_panel \- a simple panel for use with pekwm


.SH SYNOPSIS
.PP
pekwm\_panel [\-\-display]


.SH DESCRIPTION
.PP
pekwm\_panel is a simple panel application bundled together with pekwm.


.SH OPTIONS
.PP
\fB\-\-help\fP Show help information.

.PP
\fB\-\-config\fP \fIPATH\fP Use panel configuration at \fIPATH\fP\&.

.PP
\fB\-\-display\fP \fIDISPLAY\fP Connect to DISPLAY instead of DISPLAY set in environment.

.PP
\fB\-\-pekwm\-config\fP \fIPATH\fP Read active theme from pekwm configuration at \fIPATH\fP\&.

.PP
\fB\-\-log\-level\fP \fILEVEL\fP Log level.

.PP
\fB\-\-log\-file\fP \fIPATH\fP Log to \fIPATH\fP, use \- for stdout.
