.nh
.TH pekwm 1 "February 2021" pekwm "User Manual"

.SH NAME
.PP
pekwm \- a tabbed window manager


.SH SYNOPSIS
.PP
pekwm [\-\-display]


.SH DESCRIPTION
.PP
pekwm is a tabbed window manager which focuses on being highly
configurable. pekwm has a rich feature set including:

.RS
.IP \(bu 2
Autoproperties, set properties and group windows automatically based on type or title.
.IP \(bu 2
Keychains, multi\-level keybindings.
.IP \(bu 2
XRandR and Xinerama support.

.RE

.PP
For more information about the pekwm project and for full
documentation, visit http://www.pekwm.se.


.SH OPTIONS
.PP
\fB\-\-help\fP Show help information.

.PP
\fB\-\-version\fP Show version information.

.PP
\fB\-\-info\fP Show information about compiled in features.

.PP
\fB\-\-display\fP \fIDISPLAY\fP Connect to DISPLAY instead of DISPLAY set in environment.

.PP
\fB\-\-config\fP \fICONFIG\fP Use CONFIG file instead of default ~/.pekwm/config

.PP
\fB\-\-replace\fP Replace running window manager.
