.nh
.TH pekwm\_theme 1 "February 2021" pekwm\_theme "User Manual"

.SH NAME
.PP
pekwm\_theme \- theme management for pekwm


.SH SYNOPSIS
.PP
pekwm\_theme [install|uninstall|show|search]


.SH DESCRIPTION
.PP
pekwm\_theme is a theme manager for pekwm that handles \fIinstallation\fP,
\fIremoval\fP, \fIsearch\fP and \fIpreview\fP operations on themes available in
the pekwm\-theme\-index (https://github.com/pekwm/pekwm\-theme\-index/)
and published on the pekwm theme site (https://www.pekwm.se/themes/).


.SH OPTIONS
.PP
\fBinstall\fP, install theme with provided name.

.PP
\fBuninstall\fP, uninstall theme with provided name. Will delete local modifications, use with care.

.PP
\fBshow\fP, show preview of theme with provided name.

.PP
\fBsearch\fP, search for themes matching the provided pattern (grep).
