#!/bin/sh
#
# This file is in the public domain. Anyone is free to copy, modify, publish
# use, sell or distribute for any purpose, commercial or non-commercial, and by
# any means.
#
# pekwm start shell script run when pekwm starts excluding restarts.
#
# The file must be marked executable for it to be executed:
#
# chmod +x ~/.pekwm/start
#
# Execution of the file can be skipped by passing --skip-start to pekwm.
# 
